version: '2'
services:
    app-kafka:
        image: bghali/kafkacluster:latest
        hostname: kafka-local
        ports:
            - "4049:4040"
        links:
            - "postgres-local"
        depends_on:
            - postgres-local
        
          
    postgres-local: 
        image: bghali/postgres:latest
        hostname: postgres-local
        expose:
            - "5432"
        volumes:
            - data-volume:/var/lib/backup/data

volumes:
   data-volume:
